# Generated by Django 4.2.7 on 2024-01-04 15:40

from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnxietyTestQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.CharField(blank=True, max_length=200, null=True, verbose_name='Вопрос')),
            ],
            options={
                'verbose_name': 'Вопрос теста "Шкала тревоги Бэка"',
                'verbose_name_plural': 'Вопросы теста "Шкала тревоги Бэка"',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='FoodbehaviorTestQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.CharField(blank=True, max_length=200, null=True, verbose_name='Вопрос')),
            ],
            options={
                'verbose_name': 'Вопрос теста "Шкала пищевого поведения"',
                'verbose_name_plural': 'Вопросы теста "Шкала пищевого поведения"',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='ImpulsivityTestQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.CharField(blank=True, max_length=200, null=True, verbose_name='Вопрос')),
            ],
            options={
                'verbose_name': 'Вопрос теста "Шкала импульсивности Барратта"',
                'verbose_name_plural': 'Вопросы теста "Шкала импульсивности Барратта"',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.CharField(blank=True, max_length=200, null=True, verbose_name='Вопрос')),
            ],
            options={
                'verbose_name': 'Вопрос теста "Шкала депрессии Бэка"',
                'verbose_name_plural': 'Вопросы теста "Шкала депрессии Бэка"',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='SelfcompassionTestQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.CharField(blank=True, max_length=200, null=True, verbose_name='Вопрос')),
            ],
            options={
                'verbose_name': 'Вопрос теста "Шкала самосострадания Кристин Нефф"',
                'verbose_name_plural': 'Вопросы теста "Шкала самосострадания Кристин Нефф"',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('first_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Имя')),
                ('second_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Фамилия')),
                ('middle_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Отчество')),
                ('email', models.EmailField(blank=True, max_length=254, unique=True)),
                ('phone_number', models.CharField(blank=True, max_length=15, verbose_name='Номер телефона')),
                ('date_of_birth', models.DateField(blank=True, max_length=15, null=True, verbose_name='Дата рождения')),
                ('groups', models.ManyToManyField(blank=True, related_name='custom_users', to='auth.group', verbose_name='Группы')),
                ('user_permissions', models.ManyToManyField(blank=True, related_name='custom_users', to='auth.permission', verbose_name='Права пользователя')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='TestResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(verbose_name='Баллы')),
                ('result_message', models.CharField(blank=True, max_length=255, null=True, verbose_name='Описание результата')),
                ('date_completed', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата прохождения')),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='test_results', to=settings.AUTH_USER_MODEL, verbose_name='Имя')),
            ],
            options={
                'verbose_name': 'Результат клиента "Шкала депресии Бэка"',
                'verbose_name_plural': 'Результат клиента "Шкала депресии Бэка"',
            },
        ),
        migrations.CreateModel(
            name='SelfcompassionTestResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField(blank=True, null=True, verbose_name='Баллы')),
                ('result_message', models.CharField(blank=True, max_length=255, null=True, verbose_name='Описание результата')),
                ('date_completed', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата прохождения')),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('kindness_score', models.FloatField(verbose_name='Доброта к себе')),
                ('self_blame_score', models.FloatField(verbose_name='Самоосуждение')),
                ('human_commonality_score', models.FloatField(verbose_name='Человеческая общность')),
                ('isolation_score', models.FloatField(verbose_name='Изоляция')),
                ('mindfulness_score', models.FloatField(verbose_name='Осознанность')),
                ('overidentification_score', models.FloatField(verbose_name='Сверхидентификация')),
                ('total_score', models.FloatField(verbose_name='Общий балл')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='selfcompassion_test_results', to=settings.AUTH_USER_MODEL, verbose_name='Имя')),
            ],
            options={
                'verbose_name': 'Результат клиета "Шкала самосострадания Кристин Нефф"',
                'verbose_name_plural': 'Результаты клиетов "Шкала самосострадания Кристин Нефф"',
            },
        ),
        migrations.CreateModel(
            name='SelfcompassionTestChoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice_text', models.CharField(max_length=300, null=True, verbose_name='Варианты ответов')),
                ('points', models.IntegerField(default=0, verbose_name='Баллы')),
                ('question', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='PsichologyTest.selfcompassiontestquestion')),
            ],
        ),
        migrations.CreateModel(
            name='ImpulsivityTestResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(verbose_name='Баллы')),
                ('result_message', models.CharField(blank=True, max_length=255, null=True, verbose_name='Описание результата')),
                ('date_completed', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата прохождения')),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='impulsivity_test_results', to=settings.AUTH_USER_MODEL, verbose_name='Имя')),
            ],
            options={
                'verbose_name': 'Результат клиета "Шкала импульсивности Барратта"',
                'verbose_name_plural': 'Результаты клиетов "Шкала импульсивности Барратта"',
            },
        ),
        migrations.CreateModel(
            name='ImpulsivityTestChoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice_text', models.CharField(max_length=300, null=True, verbose_name='Варианты ответов')),
                ('points', models.IntegerField(default=0, verbose_name='Баллы')),
                ('question', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='PsichologyTest.impulsivitytestquestion', verbose_name='Вопросы')),
            ],
        ),
        migrations.CreateModel(
            name='FoodbehaviorTestResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_completed', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата прохождения')),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('thinness_striving_score', models.IntegerField(verbose_name='Стремление к худобе')),
                ('thinness_striving_stenain', models.IntegerField(default=0, verbose_name='Стенайн "Стремление к худобе"')),
                ('bulimia_score', models.IntegerField(verbose_name='Булимия')),
                ('bulimia_stenain', models.IntegerField(default=0, verbose_name='Стенайн "Булимия"')),
                ('body_dissatisfaction_score', models.IntegerField(verbose_name='Неудовлетворенность телом')),
                ('body_dissatisfaction_stenain', models.IntegerField(default=0, verbose_name='Стенайн "Неудовлетворенность телом"')),
                ('ineffectiveness_score', models.IntegerField(verbose_name='Неэффективность')),
                ('ineffectiveness_stenain', models.IntegerField(default=0, verbose_name='Стенайн "Неэффективность"')),
                ('perfectionism_score', models.IntegerField(verbose_name='Перфекционизм')),
                ('perfectionism_stenain', models.IntegerField(default=0, verbose_name='Стенайн "Перфекционизм"')),
                ('interpersonal_distrust_score', models.IntegerField(verbose_name='Недоверие в межличностных отношениях')),
                ('interpersonal_distrust_stenain', models.IntegerField(default=0, verbose_name='Стенайн "Недоверие в межличностных отношениях"')),
                ('interoceptive_incompetence_score', models.IntegerField(verbose_name='Интероцептивная некомпетентность')),
                ('interoceptive_incompetence_stenain', models.IntegerField(default=0, verbose_name='Стенайн "Интероцептивная некомпетентность"')),
                ('result_message', models.CharField(blank=True, max_length=255, null=True, verbose_name='Описание результата')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='food_behavior_results', to=settings.AUTH_USER_MODEL, verbose_name='Имя')),
            ],
            options={
                'verbose_name': 'Результат клиента "Шкала пищевого поведения"',
                'verbose_name_plural': 'Результаты клиентов "Шкала пищевого поведения"',
            },
        ),
        migrations.CreateModel(
            name='FoodbehaviorTestChoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice_text', models.CharField(max_length=300, null=True, verbose_name='Варианты ответов')),
                ('points', models.IntegerField(default=0, verbose_name='Баллы')),
                ('question', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='PsichologyTest.foodbehaviortestquestion')),
            ],
        ),
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice_text', models.CharField(max_length=300, null=True, verbose_name='Варианты ответов')),
                ('points', models.IntegerField(default=0, verbose_name='Баллы')),
                ('question', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='PsichologyTest.question')),
            ],
        ),
        migrations.CreateModel(
            name='AnxietyTestResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(verbose_name='Баллы')),
                ('result_message', models.CharField(blank=True, max_length=255, null=True, verbose_name='Описание результата')),
                ('date_completed', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата прохождения')),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='anxiety_test_results', to=settings.AUTH_USER_MODEL, verbose_name='Имя')),
            ],
            options={
                'verbose_name': 'Результат клиета "Шкала тревоги Бэка"',
                'verbose_name_plural': 'Результаты клиетов "Шкала тревоги Бэка"',
            },
        ),
        migrations.CreateModel(
            name='AnxietyTestChoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice_text', models.CharField(max_length=300, null=True, verbose_name='Варианты ответов "Шкала тревоги Бэка"')),
                ('points', models.IntegerField(default=0, verbose_name='Баллы "Шкала тревоги Бэка"')),
                ('question', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='PsichologyTest.anxietytestquestion', verbose_name='Вопрос')),
            ],
        ),
    ]
